OPENAI_API_KEY = "sk-xxxx"
OPENAI_MODEL = "qwen3-vl-flash-2026-01-22"
OPENAI_VL_MODEL = "qwen3-vl-flash-2026-01-22"
OPENAI_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"

NEO4J_URI = "neo4j+s://xxxx.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "xxxx"
NEO4J_DATABASE = "neo4j"
